//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_vrcontrol : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single ForwardThrust
        {
            get
            {
                return SteamVR_Actions.vrcontrol_ForwardThrust;
            }
        }
        
        public virtual SteamVR_Action_Single BackwardThrust
        {
            get
            {
                return SteamVR_Actions.vrcontrol_BackwardThrust;
            }
        }
        
        public virtual SteamVR_Action_Boolean Boost
        {
            get
            {
                return SteamVR_Actions.vrcontrol_Boost;
            }
        }
        
        public virtual SteamVR_Action_Vector2 HVThrust
        {
            get
            {
                return SteamVR_Actions.vrcontrol_HVThrust;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PitchRoll
        {
            get
            {
                return SteamVR_Actions.vrcontrol_PitchRoll;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Yaw
        {
            get
            {
                return SteamVR_Actions.vrcontrol_Yaw;
            }
        }
    }
}
