//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_vrcontrol : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single ForwardThrust
        {
            get
            {
                return SteamVR_Actions.vrcontrol_ForwardThrust;
            }
        }
        
        public virtual SteamVR_Action_Single BackwardThrust
        {
            get
            {
                return SteamVR_Actions.vrcontrol_BackwardThrust;
            }
        }
        
        public virtual SteamVR_Action_Boolean Boost
        {
            get
            {
                return SteamVR_Actions.vrcontrol_Boost;
            }
        }
        
        public virtual SteamVR_Action_Vector2 HVThrust
        {
            get
            {
                return SteamVR_Actions.vrcontrol_HVThrust;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PitchRoll
        {
            get
            {
                return SteamVR_Actions.vrcontrol_PitchRoll;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabJoystick
        {
            get
            {
                return SteamVR_Actions.vrcontrol_GrabJoystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_A
        {
            get
            {
                return SteamVR_Actions.vrcontrol_Left_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right_A
        {
            get
            {
                return SteamVR_Actions.vrcontrol_Right_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left_B
        {
            get
            {
                return SteamVR_Actions.vrcontrol_Left_B;
            }
        }
        
        public virtual SteamVR_Action_Vector2 POV1_POS
        {
            get
            {
                return SteamVR_Actions.vrcontrol_POV1_POS;
            }
        }
        
        public virtual SteamVR_Action_Vector2 POV2_POS
        {
            get
            {
                return SteamVR_Actions.vrcontrol_POV2_POS;
            }
        }
        
        public virtual SteamVR_Action_Boolean POV1_TOUCH
        {
            get
            {
                return SteamVR_Actions.vrcontrol_POV1_TOUCH;
            }
        }
        
        public virtual SteamVR_Action_Boolean POV2_TOUCH
        {
            get
            {
                return SteamVR_Actions.vrcontrol_POV2_TOUCH;
            }
        }
        
        public virtual SteamVR_Action_Boolean UI_ENTER
        {
            get
            {
                return SteamVR_Actions.vrcontrol_UI_ENTER;
            }
        }
        
        public virtual SteamVR_Action_Boolean UI_BACK
        {
            get
            {
                return SteamVR_Actions.vrcontrol_UI_BACK;
            }
        }
    }
}
